update

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -9,52 +9,66 @@
 
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
-	against=HEAD
+    against=HEAD
 else
-	# Initial commit: diff against an empty tree object
-	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+    # Initial commit: diff against an empty tree object
+    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
 
-# If you want to allow non-ascii filenames set this variable to true.
-allownonascii=$(git config hooks.allownonascii)
+# If you want to allow non-ASCII filenames set this variable to true.
+allownonascii=$(git config --bool hooks.allownonascii)
 
-# Cross platform projects tend to avoid non-ascii filenames; prevent
+# Redirect output to stderr.
+exec 1>&2
+
+# Cross platform projects tend to avoid non-ASCII filenames; prevent
 # them from being added to the repository. We exploit the fact that the
 # printable range starts at the space character and ends with tilde.
 if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test "$(git diff --cached --name-only --diff-filter=A -z $against |
-	  LC_ALL=C tr -d '[ -~]\0')"
+    # Note that the use of brackets around a tr range is ok here, (it's
+    # even required, for portability to Solaris 10's /usr/bin/tr), since
+    # the square bracket bytes happen to fall in the designated range.
+    test $(git diff --cached --name-only --diff-filter=A -z $against |
+      LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
 then
-	echo "Error: Attempt to add a non-ascii file name."
-	echo
-	echo "This can cause problems if you want to work"
-	echo "with people on other platforms."
-	echo
-	echo "To be portable it is advisable to rename the file ..."
-	echo
-	echo "If you know what you are doing you can disable this"
-	echo "check using:"
-	echo
-	echo "  git config hooks.allownonascii true"
-	echo
-	exit 1
+    cat <<\EOF
+Error: Attempt to add a non-ASCII file name.
+
+This can cause problems if you want to work with people on other platforms.
+
+To be portable it is advisable to rename the file.
+
+If you know what you are doing you can disable this check using:
+
+  git config hooks.allownonascii true
+EOF
+    exit 1
 fi
 
+# If there are whitespace errors, print the offending file names and fail.
+#exec git diff-index --check --cached $against --
+#convert file
 if test $(git diff --cached --name-status | awk '{if ($1 != "D") print $2}'| wc -c) != 0
 then
-    phpFiles=$(git diff --cached --name-status | awk '{if ($1 != "D") print $2}'| grep -E '\.php' | xargs)
-    for file in $phpFiles;
-    do
-        if test "$(/apps/php/bin/php -l $file | grep -v 'No syntax errors')"
+    files=$(git diff --cached --name-status | awk '{if ($1 != "D") print $2}'| grep -E '\.php|\.html|\.js' | xargs)
+    phpFiles=$(git diff --cached --name-status | awk '{if ($1 != "D") print $2}'| grep '.php' | xargs)
+
+    errors=0
+    for file in $phpFiles; do
+        message=`php -l $file | grep -v 'No syntax errors'`
+        if [ "$message" != '' ]
         then
-            echo "Error: There is fatal error in $file"
-            exit 1
+            errors=1
+            echo $message
         fi
     done
-    files=$(git diff --cached --name-status | awk '{if ($1 != "D") print $2}'| grep -E '\.php|\.html|\.js' | xargs)
+
+    if [ "$errors" != "0" ]
+    then
+        echo "Error"
+        exit 1
+    fi
+
     # delete bom
     sed -i 's/\xEF\xBB\xBF//g' $files
     # convert CRLF to LF
@@ -63,7 +77,8 @@ then
     sed -i "s/\t/    /g" $files
     # delete trail space
     sed -i "s/ *$//g" $files
+    # delete最后的空行
+    sed -i '${/^$/d}' $files
     # re-add the files
     git add $files
 fi
-exec git diff-index --check --cached $against --
